version: '3.8'

services:
    web:
        build: .
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/home/jzonkey/Documents/panoptes-tom
        ports:
        - 8000:8000
        env_file:
        - /home/jzonkey/Documents/panoptes-tom/.env