version: '3.8'

services:
    web:
        build: .
        depends_on:
            - tom_postgres_db
        command: python3 manage.py runserver 0.0.0.0:8080
        volumes:
            - .:/app
        ports:
        - 8080:8080
        - 8000:8000
        env_file:
        - .env
    tom_postgres_db:
        image: gcr.io/cloudsql-docker/gce-proxy:1.16
        ports:
            - 3306:3306
        command: ./cloud_sql_proxy -instances=${INSTANCE_CONNECTION_NAME}=tcp:0.0.0.0:3306 -credential_file=/config
        volumes:
        - ${GOOGLE_APPLICATION_CREDENTIALS}:/config
        restart: always