version: '3.8'

services:
      # postgres
#   db:
#     image: postgres
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_DB=postgres

    web:
        build: .
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
        - ./panoptes-tom/:/usr/src/panoptes-tom/
        ports:
        - 8000:8000
        env_file:
        - ./.env.dev


    db:
        image: postgres
        volumes:
          - postgres_data:/var/lib/postgresql/data/
        environment:
          - POSTGRES_USER=hello_django
          - POSTGRES_PASSWORD=hello_django
          - POSTGRES_DB=hello_django_dev

volumes:
    postgres_data: